---
title: "Análisis Espacial del Dengue"
author: "Felipe Antonio Dzul Manzanilla"
date: '2022: Last compiled `r Sys.Date()`'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - default
      - default-fonts
      - duke-blue
      - hygge-duke
      - libs/cc-fonts.css
      - libs/figure-captions.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: left, top

```{r xaringan-fit-screen, echo=FALSE}
xaringanExtra::use_fit_screen()
```

```{r xaringanExtra, echo = FALSE}
xaringanExtra::use_progress_bar(color = "#0051BA", location = "top")
```

```{r xaringan-tachyons, echo=FALSE}
xaringanExtra::use_tachyons()
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "https://www.gob.mx/cms/uploads/action_program/main_image/26942/post_post_portadavectores.gif",
  width = "110px",
  height = "228px",
  position = xaringanExtra::css_position(top = "1em", right = "1em")
)
```

### Ciclo de Vida del Programa de Prevención y Control del Dengue

```{r, dpi=300,echo=FALSE, fig.align ="center", out.height="100%",out.width = "100%"}
DiagrammeR::grViz("digraph {

  # graph definitions
  graph [layout = dot, rankdir = TB]
  
  # node definitions
  node [shape = circle, style = filled, color = grey,
  fixedsize = true, width = 2] 
  
  ###########
  prog_den [label = 'Programa de Dengue',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'black']
  brote [label = 'Brote',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  cp [label = 'Control de Probables',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  node [shape = circle, style = filled, color = grey] 
 
  
  ovitraps [label = 'Ovitrampas',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  adult [label = 'Colecta de Adultos',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  enc_ver [label = 'Encuesta Verificación',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  plat [label = 'Plataforma',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
  
  #########
  node [shape = rectangle, style = filled, color = grey, fixedsize = true, width = 2.5] 
  act [label = 'Casos Actuales',  fillcolor = 'DarkOrange', color = 'white', fontcolor = 'black']
 
  epi [label = 'Vigilancia Epidemiológica',  fillcolor = 'SeaGreen', color = 'white', fontcolor = 'black']
  ent [label = 'Vigilancia Entomológica',  fillcolor = 'SeaGreen', color = 'white', fontcolor = 'black']
 ind [label = 'Indicadores',  fillcolor = 'SeaGreen', color = 'white', fontcolor = 'black']
  ###################
  prog_den -> {epi, ent}[penwidth = 4]
  
  
  act -> {
  brote[arrowhead = crow, arrowtail = box, color = 'Maroon']
  cp[arrowhead = crow, arrowtail = box, color = 'Maroon']
  } -> plat[penwidth = 4]
  epi -> {act}[penwidth = 4]
  ent -> {adult, 
  ovitraps,
  enc_ver} -> plat[penwidth = 4]  
  plat -> ind[penwidth = 4]
  ind -> prog_den[penwidth = 4]
  #ind -> {enc_ver, ovitraps, adult, cl, irs, cp, brote}

 
 
 
  }", 
  height = 550)

```




---
### **Análisis espacial de la transmision del  dengue**
<hr style="height:2px;border-width:0;color:#330019;background-color:#330019">

```{r, echo=FALSE, out.width='100%', fig.align='center'}
DiagrammeR::grViz("digraph {
                  # graph definitions
  graph [layout = dot, rankdir = TB]
  
  # node definitions
  node [shape = rectangle, 
  style = filled, 
  color = grey, 
  nodesep = .5,
  fixedsize = true, 
  width = 2.5] 
  
  # edge definition
  edge [color = grey, arrowhead = normal, arrowtail = dot]
  
  ##### epidemiological data
  
  epi [label = 'Vigilancia Epidemiológica',  fillcolor =  '#DB4437', color = 'white', fontcolor = 'white']
  data_historic [label = 'Datos Históricos',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_datos_actuales [label = 'Datos Actuales',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_acumulados [label = 'Datos Acumulados',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_trans_activa [label = 'Transmisión Activa',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  
  
  ##### Spatial Data
  
  areal [label = 'Areal Data',  fillcolor =  '#0F9D58', color = 'white', fontcolor = 'white']
  pp_data [label = 'Point Pattern Data',  fillcolor =  ' #0F9D58', color = 'white', fontcolor = 'white']
  
  
 
 # Análisis 
 hotspots [label = 'Hotspots Analysis',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 cadenas [label = 'Cadenas de Transmisión',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 cluster_ana [label = 'Cluster Analysis',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 lgcp [label = 'Spatial LGCP',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 
 
 # software
 
 geoda [label = 'Geoda',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 cluster_s [label = 'ClusterSeer',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 satscan [label = 'SatScan',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 
 r_rstudio [label = 'R & RStudio',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']

  denhotspot [label = 'denhotspots Package',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white'] 
 
 ##### define the relation
 
 epi -> {data_historic  data_datos_actuales}
 data_historic -> areal -> hotspots -> geoda
 data_datos_actuales -> {data_acumulados, data_trans_activa} -> pp_data -> {cadenas cluster_ana lgcp}
 cadenas -> cluster_s
 cluster_ana -> satscan
 
 {geoda cluster_s satscan lgcp} -> r_rstudio -> denhotspot
 
}")

```



---
### **Análisis Espacial del Vector del Dengue**
<hr style="height:2px;border-width:0;color:#330019;background-color:#330019">

```{r, echo=FALSE, out.width='100%', fig.align='center'}
DiagrammeR::grViz("digraph {
                  # graph definitions
  graph [layout = dot, rankdir = TB]
  
  # node definitions
  node [shape = rectangle, 
  style = filled, 
  color = grey, 
  nodesep = .5,
  fixedsize = true, 
  width = 2.5] 
  
  # edge definition
  edge [color = grey, arrowhead = normal, arrowtail = dot]
  
  ##### entomological data
  
  ento [label = 'Vigilancia Entomológica',  fillcolor =  '#FF5A5F', color = 'white', fontcolor = 'white']
  data_historic [label = 'Datos Históricos',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  
  years  [label = '2014-2019',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_datos_actuales [label = 'Datos del Año Actual',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_acumulados [label = 'Datos hasta la Semana Actual',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_trans_activa [label = 'Semana Actual',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  
  
  ##### Spatial Data
  
  geo_data [label = 'Geoestatistical Data',  fillcolor =  '#0F9D58', color = 'white', fontcolor = 'white']
 
  
 
 # Análisis 
 spde [label = 'SPDE-INLA',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 hotspots [label = 'Hotspots Analysis',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 #prediction [label = 'Predicción Espacial de Huevos',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 
 # entomological study
 ovitraps [label = 'Ovitrampas',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
  enc_ver [label = 'Encuesta-Verificación',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
  adults [label = 'Colecta de Adultos',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 
 
 # software
 r_rstudio [label = 'R & RStudio',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 deneggs [label = 'deneggs Package',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white'] 
 
 
 
 
 ##### define the relation
 
 
 ento -> {ovitraps  enc_ver adults} 
 
 {ovitraps adults} -> geo_data -> {data_historic data_datos_actuales}
 data_historic -> years
 
 data_datos_actuales -> {data_acumulados data_trans_activa}
 
 {years data_acumulados data_trans_activa} ->spde -> hotspots
 
 {hotspots} -> r_rstudio -> deneggs
 
}")

```



---
## Dios Botic!
<hr style="height:2px;border-width:0;color:#330019;background-color:#330019">
&nbsp;

- ***Bio*** : https://fdzul.github.io/web_site_fadm/

- ***email***       :     [felipe.dzul.m@gmail.com]()

- ***celular***     :     [8139945623]()

- ***slides***:     https://animated-longma-729cee.netlify.app/talks/spatial_analysis_dengue/#1





.footnote[La presentación fue creada via [**xaringan**](https://github.com/yihui/xaringan),
[**revealjs**](https://revealjs.com/),
[remark.js](https://remarkjs.com), [**knitr**](http://yihui.name/knitr),
& [R Markdown](https://rmarkdown.rstudio.com) en [R]() & [RStudio](2.R_Scripts/libs/rstudio_leaflet/rstudio_leaflet.css).]